site_name: SyMon
site_url: https://maswag.github.io/SyMon
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
  palette:
    primary: light blue

nav:
  - Home: .
  - Getting Started: getting_started.md
  - Installation: install.md
  - Examples: examples.md
  - Syntax: syntax.md
  - Tools: tools.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

repo_url: https://github.com/MasWag/SyMon
edit_uri: blob/master/docs/src/
docs_dir: src
