name: Boost.Test

on:
  push:
  pull_request:

jobs:
  unit_test_container:
    name: Container
    runs-on: ubuntu-latest
    container:
      image: maswag/monaa-test-env
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build and test
        run: |
          export CC=/usr/bin/gcc
          export CXX=/usr/bin/g++
          mkdir -p gcc_build
          cd gcc_build
          cmake ..
          make unit_test
          ./unit_test

  noble:
    name: Ubuntu Noble (24.04)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            build-essential \
            libppl-dev \
            libboost-all-dev \
            cmake \
            libgmp-dev \
            git
      - run: mkdir -p build && cd build && cmake .. && make unit_test && ./unit_test

  jammy:
    name: Ubuntu Jammy (22.04)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            build-essential \
            libppl-dev \
            libboost-all-dev \
            cmake \
            libgmp-dev \
            git
      - run: mkdir -p build && cd build && cmake .. && make unit_test && ./unit_test

  noble-arm:
    name: Ubuntu Noble ARM
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            build-essential \
            libppl-dev \
            libboost-all-dev \
            cmake \
            libgmp-dev \
            git
      - run: mkdir -p build && cd build && cmake .. && make unit_test && ./unit_test

  jammy-arm:
    name: Ubuntu Jammy ARM
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            build-essential \
            libppl-dev \
            libboost-all-dev \
            cmake \
            libgmp-dev \
            git
      - run: mkdir -p build && cd build && cmake .. && make unit_test && ./unit_test

  sequoia:
    name: macOS Sequoia (15)
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: brew update && brew uninstall cmake && brew install boost gmp cmake ppl
      - run: |
          mkdir -p build
          cd build
          cmake ..
          make unit_test
          ./unit_test

  sonoma:
    name: macOS Sonoma (14)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: brew update && brew uninstall cmake && brew install boost gmp cmake ppl
      - run: |
          mkdir -p build
          cd build
          cmake ..
          make unit_test
          ./unit_test

  ventura:
    name: macOS Ventura (13)
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: brew update && brew uninstall cmake && brew install boost gmp cmake ppl
      - run: |
          mkdir -p build
          cd build
          cmake ..
          make unit_test
          ./unit_test
