name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - new_syntax
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tag
        id: set-tag
        run: |
          if [[ "${GITHUB_REF##*/}" == "master" ]]; then
            echo "tag=maswag/symon:latest" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF##*/}" == "new_syntax" ]]; then
            echo "tag=maswag/symon:new_syntax" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.set-tag.outputs.tag }}
